# Generated by Django 5.2.8 on 2026-08-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=70)),
                ('code', models.CharField(max_length=20)),
                ('status', models.IntegerField(default=1)),
                ('short_code', models.CharField(max_length=20, null=True)),
                ('priority', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'course_course_category',
            },
        ),
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('code', models.CharField(max_length=20)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'course_course_type',
            },
        ),
    ]
