# Generated by Django 5.2.8 on 2026-08-26 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecategory',
            name='short_code',
        ),
    ]
