# Generated by Django 5.2.8 on 2026-09-10 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0003_campus_courseadmittedbatch_coursedegree_coursesdg_and_more'),
        ('program', '0032_courserequesttrackingstatus_campus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='program_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='program.programlevel'),
        ),
    ]
