# Generated by Django 5.2.8 on 2026-09-10 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0004_alter_course_program_type'),
        ('program', '0032_courserequesttrackingstatus_campus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselevels',
            name='program_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='program.programlevel'),
        ),
    ]
