# Generated by Django 5.2.8 on 2026-08-26 10:04

import datetime
import django.db.models.deletion
import program.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('course_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramBatches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=1)),
            ],
            options={
                'db_table': 'program_batches',
            },
        ),
        migrations.CreateModel(
            name='ProgramHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=1)),
            ],
            options={
                'db_table': 'program_head',
            },
        ),
        migrations.CreateModel(
            name='ProgramLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=1)),
            ],
            options={
                'db_table': 'program_level',
            },
        ),
        migrations.CreateModel(
            name='ProgramRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=1)),
            ],
            options={
                'db_table': 'program_ref',
            },
        ),
        migrations.CreateModel(
            name='ProgramSchools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=1)),
            ],
            options={
                'db_table': 'program_schools',
            },
        ),
        migrations.CreateModel(
            name='ProgramStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=0)),
            ],
            options={
                'db_table': 'program_status',
            },
        ),
        migrations.CreateModel(
            name='ProgramStreams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=1)),
            ],
            options={
                'db_table': 'program_streams',
            },
        ),
        migrations.CreateModel(
            name='ProgramType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=1)),
            ],
            options={
                'db_table': 'program_type',
            },
        ),
        migrations.CreateModel(
            name='ProgramLevelCreditMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_credits', models.IntegerField(null=True)),
                ('status', models.BooleanField(default=1)),
                ('program_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.programlevel')),
            ],
            options={
                'db_table': 'program_level_credit_mapping',
            },
        ),
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_no', models.CharField(max_length=15, null=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, null=True)),
                ('minimum_credits', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('program_level_credits', models.FloatField(blank=True, null=True)),
                ('status', models.BooleanField(default=1)),
                ('program_structure_pdf', models.FileField(blank=True, null=True, upload_to=program.models.program_structure_path)),
                ('program_structure_xl', models.FileField(blank=True, null=True, upload_to=program.models.program_structure_path)),
                ('po', models.IntegerField(blank=True, null=True)),
                ('pso', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('active_step', models.IntegerField(default=1)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('program_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='program.programbatches')),
                ('program_head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='program.programhead')),
                ('program_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='program.programlevel')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='program.programschools')),
                ('program_stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='program.programstreams')),
                ('program_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='program.programtype')),
            ],
            options={
                'db_table': 'programs',
            },
        ),
        migrations.CreateModel(
            name='ProgramPoPsoMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po', models.JSONField(null=True)),
                ('pso', models.JSONField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.programs')),
            ],
            options={
                'db_table': 'program_po_pso_mapping',
            },
        ),
        migrations.CreateModel(
            name='ProgramCourseStructureMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_credits', models.IntegerField(null=True)),
                ('percentage_of_credits', models.FloatField(null=True)),
                ('hons_credits', models.IntegerField(null=True)),
                ('hons_percentage_of_credits', models.FloatField(null=True)),
                ('research_credits', models.IntegerField(null=True)),
                ('research_percentage_of_credits', models.FloatField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('course_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_management.coursecategory')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.programs')),
            ],
            options={
                'db_table': 'program_course_structure_mapping',
            },
        ),
        migrations.CreateModel(
            name='ProgramStreamLevelPOPSOMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po', models.IntegerField(null=True)),
                ('pso', models.IntegerField(null=True)),
                ('status', models.BooleanField(default=1)),
                ('program_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.programlevel')),
                ('program_stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.programstreams')),
            ],
            options={
                'db_table': 'program_stream_level_po_pso_mapping',
            },
        ),
        migrations.CreateModel(
            name='ProgramTrackingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('campus', models.CharField(max_length=100, null=True)),
                ('institution', models.CharField(max_length=100, null=True)),
                ('department', models.CharField(max_length=100, null=True)),
                ('created', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('designation', models.CharField(max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('emp_id', models.CharField(max_length=15, null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProgramTrackingStatus_program', to='program.programs')),
                ('program_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProgramTrackingStatus_program_status', to='program.programstatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProgramTrackingStatus_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'program_tracking_status',
            },
        ),
        migrations.CreateModel(
            name='ProgramTrackingUserMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_edit', models.IntegerField(default=0)),
                ('program_tracking_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProgramTrackingUserMapping_project_tracking_status', to='program.programtrackingstatus')),
                ('programs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.programs')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProgramTrackingUserMapping_to_user', to=settings.AUTH_USER_MODEL)),
                ('to_user_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProgramTrackingUserMapping_to_user_group', to='auth.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProgramTrackingUserMapping_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'program_tracking_user_mapping',
            },
        ),
    ]
