# Generated by Django 5.2.8 on 2026-08-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programlevelcreditmapping',
            name='minimum_credits',
            field=models.FloatField(null=True),
        ),
    ]
