# Generated by Django 5.2.8 on 2026-08-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_alter_programlevelcreditmapping_minimum_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='programschools',
            name='code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='programschools',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
