# Generated by Django 5.2.8 on 2026-08-26 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_programschools_code_alter_programschools_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='programs',
            name='program_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program_head', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ProgramHead',
        ),
    ]
