# Generated by Django 5.2.8 on 2026-08-26 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0004_alter_programs_program_head_delete_programhead'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='programs',
            name='pending_at',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Programs_pending_at', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='programs',
            name='program_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Programs_program_status', to='program.programstatus'),
        ),
    ]
