# Generated by Django 5.2.8 on 2026-08-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0005_programs_pending_at_programs_program_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='programs',
            name='duration',
            field=models.IntegerField(blank=True, choices=[(3, '3 Years'), (4, '4 Years'), (5, '5 Years')], null=True),
        ),
    ]
