# Generated by Django 5.2.8 on 2026-08-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0006_programs_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='programcoursestructuremapping',
            name='is_exit_structure',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='programs',
            name='has_exit_plan',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
