# Generated by Django 5.2.8 on 2026-08-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0007_programcoursestructuremapping_is_exit_structure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programs',
            name='exit_minimum_credits',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
