# Generated by Django 5.2.8 on 2026-08-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0008_programs_exit_minimum_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='programstreamlevelpopsomapping',
            name='peo',
            field=models.IntegerField(null=True),
        ),
    ]
