# Generated by Django 5.2.8 on 2026-08-27 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0009_programstreamlevelpopsomapping_peo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='programstreamlevelpopsomapping',
            table='program_stream_level_po_pso_peo_mapping',
        ),
    ]
