# Generated by Django 5.2.8 on 2026-08-27 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0010_alter_programstreamlevelpopsomapping_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProgramStreamLevelPOPSOMapping',
            new_name='ProgramStreamLevelPOPSOPEOMapping',
        ),
    ]
