# Generated by Django 5.2.8 on 2026-08-27 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0011_rename_programstreamlevelpopsomapping_programstreamlevelpopsopeomapping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programs',
            name='po',
        ),
        migrations.RemoveField(
            model_name='programs',
            name='pso',
        ),
    ]
