# Generated by Django 5.2.8 on 2026-08-27 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0012_remove_programs_po_remove_programs_pso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programs',
            name='name',
        ),
    ]
