# Generated by Django 5.2.8 on 2026-08-27 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0013_remove_programs_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TracksHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=1)),
            ],
            options={
                'db_table': 'tracks_header',
            },
        ),
        migrations.CreateModel(
            name='TrackHeaderLevelSchoolMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=1)),
                ('program_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.programlevel')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.programschools')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.tracksheader')),
            ],
            options={
                'db_table': 'track_header_level_school_mapping',
            },
        ),
    ]
