# Generated by Django 5.2.8 on 2026-08-27 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0014_tracksheader_trackheaderlevelschoolmapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramSchoolDurationExitplanMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(null=True)),
                ('exit_plan', models.BooleanField(default=0)),
                ('status', models.BooleanField(default=1)),
                ('program_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.programlevel')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.programschools')),
            ],
            options={
                'db_table': 'program_school_duration_exitplan_mapping',
            },
        ),
    ]
