# Generated by Django 5.2.8 on 2026-08-31 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0015_programschooldurationexitplanmapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programs',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
