# Generated by Django 5.2.8 on 2026-08-31 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0002_remove_coursecategory_short_code'),
        ('program', '0016_alter_programs_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramTrackCourseStructureMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_exit_structure', models.BooleanField(default=False)),
                ('no_of_credits', models.IntegerField(null=True)),
                ('percentage_of_credits', models.FloatField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('course_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_management.coursecategory')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.programs')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.tracksheader')),
            ],
            options={
                'db_table': 'program_track_course_structure_mapping',
            },
        ),
    ]
