# Generated by Django 5.2.8 on 2026-08-31 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0017_programtrackcoursestructuremapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programtrackcoursestructuremapping',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='program.tracksheader'),
        ),
        migrations.DeleteModel(
            name='ProgramCourseStructureMapping',
        ),
    ]
