# Generated by Django 5.2.8 on 2026-08-31 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0018_alter_programtrackcoursestructuremapping_track_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programstreamlevelpopsopeomapping',
            name='program_level',
        ),
        migrations.RemoveField(
            model_name='programstreamlevelpopsopeomapping',
            name='program_stream',
        ),
        migrations.CreateModel(
            name='ProgramPoPsoPEOMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome_type', models.CharField(choices=[('PO', 'PO'), ('PSO', 'PSO'), ('PEO', 'PEO')], max_length=10, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.programs')),
            ],
            options={
                'db_table': 'program_po_pso_peo_mapping',
            },
        ),
        migrations.DeleteModel(
            name='ProgramPoPsoMapping',
        ),
        migrations.DeleteModel(
            name='ProgramStreamLevelPOPSOPEOMapping',
        ),
    ]
