# Generated by Django 5.2.8 on 2026-08-31 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0019_remove_programstreamlevelpopsopeomapping_program_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programpopsopeomapping',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
