# Generated by Django 5.2.8 on 2026-08-31 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0020_programpopsopeomapping_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='programpopsopeomapping',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
