# Generated by Django 5.2.8 on 2026-08-31 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0021_programpopsopeomapping_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProgramPoPsoPEOMapping',
            new_name='ProgramOutcomesMapping',
        ),
        migrations.AlterModelTable(
            name='programoutcomesmapping',
            table='program_outcomes_mapping',
        ),
    ]
