# Generated by Django 5.2.8 on 2026-09-01 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0022_rename_programpopsopeomapping_programoutcomesmapping_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProgramBatches',
            new_name='Batches',
        ),
        migrations.RenameModel(
            old_name='ProgramSchools',
            new_name='Schools',
        ),
        migrations.RenameModel(
            old_name='ProgramStreams',
            new_name='Streams',
        ),
        migrations.AlterModelTable(
            name='batches',
            table='u_batches',
        ),
        migrations.AlterModelTable(
            name='schools',
            table='u_schools',
        ),
        migrations.AlterModelTable(
            name='streams',
            table='u_streams',
        ),
    ]
