# Generated by Django 5.2.8 on 2026-09-07 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0025_programboschistory'),
        ('usermanagement', '0007_boscochairhoddeptmapping_school'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('new', 'Float a New Course'), ('modify', 'Modify an Existing Course')], max_length=10)),
                ('dept_scope', models.CharField(choices=[('same', 'Within the Department'), ('other', 'Other Department')], max_length=10)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanagement.departments')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_requests', to='program.programs')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_requests_raised', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'program_course_request',
            },
        ),
    ]
