# Generated by Django 5.2.8 on 2026-09-07 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('program', '0026_courserequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRequestStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=1)),
            ],
            options={
                'db_table': 'course_request_status',
            },
        ),
        migrations.AddField(
            model_name='courserequest',
            name='request_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='program.courserequeststatus'),
        ),
        migrations.CreateModel(
            name='CourseRequestTrackingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('course_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_status', to='program.courserequest')),
                ('request_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.courserequeststatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'course_request_tracking_status',
            },
        ),
        migrations.CreateModel(
            name='CourseRequestTrackingUserMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_edit', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('course_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_user_mapping', to='program.courserequest')),
                ('course_request_tracking_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='program.courserequesttrackingstatus')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_request_to_user', to=settings.AUTH_USER_MODEL)),
                ('to_user_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_request_from_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'course_request_tracking_user_mapping',
            },
        ),
    ]
