# Generated by Django 5.2.8 on 2026-09-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0027_courserequeststatus_courserequest_request_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserequest',
            name='justification',
            field=models.TextField(default=''),
        ),
    ]
