# Generated by Django 5.2.8 on 2026-09-07 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0028_courserequest_justification'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='courserequeststatus',
            table='program_course_request_status',
        ),
        migrations.AlterModelTable(
            name='courserequesttrackingstatus',
            table='program_course_request_tracking_status',
        ),
        migrations.AlterModelTable(
            name='courserequesttrackingusermapping',
            table='program_course_request_tracking_user_mapping',
        ),
    ]
