# Generated by Django 5.2.8 on 2026-09-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0029_alter_courserequeststatus_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserequest',
            name='course_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
