# Generated by Django 5.2.8 on 2026-09-08 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('program', '0031_courserequest_pending_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserequesttrackingstatus',
            name='campus',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='courserequesttrackingstatus',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='courserequesttrackingstatus',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='courserequesttrackingstatus',
            name='emp_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='courserequesttrackingstatus',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
        migrations.AddField(
            model_name='courserequesttrackingstatus',
            name='institution',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='courserequesttrackingstatus',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
