# Generated by Django 5.2.8 on 2026-09-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0032_courserequesttrackingstatus_campus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programs',
            name='exit_end_of_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
