# Generated by Django 5.2.8 on 2026-09-16 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0005_courselevels_program_level'),
        ('program', '0033_programs_exit_end_of_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramCourseMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_mappings', to='course_management.course')),
                ('mapped_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_mappings', to='program.programs')),
            ],
            options={
                'db_table': 'program_course_mapping',
                'unique_together': {('program', 'course')},
            },
        ),
    ]
