"""
Django settings for CDM project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_^=clv=_8#090h7k3&c#mmt^=9el+ho42qt@81lq$^ef^zuv2a'
ENCRYPT_KEY=b'1HHrb3jhgfKD8QE2LI-hHjwybC-9cAiE7WPBzkqEHgY='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'usermanagement',
    'course_management',
    'program',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'CDM.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'CDM.wsgi.application'
LOGIN_URL='https://login.gitam.edu'
AUTH_USER_MODEL='usermanagement.User'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': 'CDM',
        'USER': 'sa',
        'PASSWORD': 'G1t2m@PythonDB_@#',
        'HOST': '192.168.64.191',
        'PORT': '',
        'OPTIONS': {
            'DRIVER': 'SQL Server Native Client 9.0',
        },
    },
    'GITAM': {
        'ENGINE': 'mssql',
        'NAME': 'GITAM',
        'USER': 'GITAMSQLDBUSER',
        'PASSWORD': 'gitam@web@123!@#',
        'HOST': '192.168.23.19',
        'PORT': '',
        'OPTIONS': {
            'DRIVER': 'SQL Server Native Client 9.0',
        },
    },
    'ACADEMIC_PROFILES': {
        'ENGINE': 'mssql',
        'NAME': 'ACADEMIC_PROFILES',
        'USER': 'sa',
        'PASSWORD': 'G1t2m@PythonDB_@#',
         'HOST': '192.168.64.191',
        'PORT': '',
        'OPTIONS': {
            'DRIVER': 'SQL Server Native Client 9.0',
        },
    },

}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
MEDIA_ROOT = os.path.join(BASE_DIR,'media/')
MEDIA_URL = '/media/'
MEDIAFILES_DIRS = [os.path.join(BASE_DIR,'media/')]


EMAIL_BACKEND  = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST     = 'smtp-relay.gmail.com'
EMAIL_PORT     = 587
EMAIL_USE_TLS  = True
#EMAIL_HOST_USER     = 'notifier@gitam.edu'   
#EMAIL_HOST_PASSWORD = 'deab gagm wthi jutl' 

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


TEST_E = [502970]

EMP_ID_2 = ['503654','502971']