# Generated by Django 5.2.8 on 2026-09-01 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0002_batches_schools_streams'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('code', models.CharField(max_length=5)),
                ('status', models.BooleanField(default=1)),
            ],
            options={
                'db_table': 'u_department',
            },
        ),
        migrations.CreateModel(
            name='BosChairSchoolMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('active_from_date', models.DateTimeField(auto_now_add=True)),
                ('active_to_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BosChairSchoolMapping_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BosChairSchoolMapping_modified_by', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanagement.schools')),
            ],
            options={
                'db_table': 'bos_chair_school_mapping',
            },
        ),
        migrations.CreateModel(
            name='BosCochairHODDeptMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('active_from_date', models.DateTimeField(auto_now_add=True)),
                ('active_to_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(null=True)),
                ('bos_cochair', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BosCochairHODDeptMapping_created_by', to=settings.AUTH_USER_MODEL)),
                ('hod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BosCochairHODDeptMapping_hod', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BosCochairHODDeptMapping_modified_by', to=settings.AUTH_USER_MODEL)),
                ('dept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanagement.departments')),
            ],
            options={
                'db_table': 'bos_cochair_hod_dept_mapping',
            },
        ),
    ]
