# Generated by Django 5.2.8 on 2026-09-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0003_departments_boschairschoolmapping_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeMaster',
            fields=[
                ('empid', models.CharField(db_column='EMPID', max_length=25, primary_key=True, serialize=False)),
                ('emp_name', models.CharField(blank=True, db_column='EMP_NAME', max_length=500, null=True)),
                ('emailid', models.CharField(blank=True, db_column='EMAILID', max_length=500, null=True)),
                ('mobile', models.CharField(blank=True, db_column='MOBILE', max_length=120, null=True)),
                ('dob', models.DateTimeField(blank=True, db_column='DOB', null=True)),
                ('doj', models.DateTimeField(blank=True, db_column='DOJ', null=True)),
                ('job_description', models.CharField(blank=True, db_column='JOB_DESCRIPTION', max_length=500, null=True)),
                ('campus', models.CharField(blank=True, db_column='CAMPUS', max_length=25, null=True)),
                ('college_code', models.CharField(blank=True, db_column='COLLEGE_CODE', max_length=25, null=True)),
                ('dept_code', models.CharField(blank=True, db_column='DEPT_CODE', max_length=50, null=True)),
            ],
            options={
                'db_table': 'EMPLOYEE_MASTER',
                'managed': False,
            },
        ),
    ]
