# Generated by Django 5.2.8 on 2026-09-01 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0004_employeemaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='boschairschoolmapping',
            name='bos_chair',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
