# Generated by Django 5.2.8 on 2026-09-01 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0005_boschairschoolmapping_bos_chair'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boschairschoolmapping',
            name='active_from_date',
        ),
        migrations.RemoveField(
            model_name='boschairschoolmapping',
            name='active_to_date',
        ),
        migrations.RemoveField(
            model_name='boscochairhoddeptmapping',
            name='active_from_date',
        ),
        migrations.RemoveField(
            model_name='boscochairhoddeptmapping',
            name='active_to_date',
        ),
    ]
