# Generated by Django 5.2.8 on 2026-09-01 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0006_remove_boschairschoolmapping_active_from_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boscochairhoddeptmapping',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanagement.schools'),
        ),
    ]
